bn_partitions: [4, 4, 4, 4, 4, 4, 4, 4, 4]
budgets: [[1, 4, 4, 1], [1, 4, 4, 1], [1, 4, 4, 1], [1, 4, 4, 1], [1, 4, 4, 1], [
    1, 4, 4, 1], [1, 4, 4, 1], [1, 4, 4, 1], [1, 4, 4, 1], [1, 4, 4, 1], [1, 4, 4,
    1], [1, 4, 4, 1], [1, 4, 4, 1], [1, 4, 4, 1], [1, 4, 4, 1], [1, 4, 4, 1], [1,
    4, 4, 1], [1, 4, 4, 1], [1, 4, 4, 1], [1, 4, 4, 1]]
initial_budget: [1, 4, 4, 1]
input_partition: [1, 1, 1, 1]
layers: [inputs, conv1.weight, layer1.0.conv1.weight, layer1.0.conv2.weight, layer1.1.conv1.weight,
  layer1.1.conv2.weight, layer2.0.conv1.weight, layer2.0.conv2.weight, layer2.0.shortcut.0.weight,
  layer2.1.conv1.weight, layer2.1.conv2.weight, layer3.0.conv1.weight, layer3.0.conv2.weight,
  layer3.0.shortcut.0.weight, layer3.1.conv1.weight, layer3.1.conv2.weight, layer4.0.conv1.weight,
  layer4.0.conv2.weight, layer4.0.shortcut.0.weight, layer4.1.conv1.weight, layer4.1.conv2.weight]
maps: [[0, 1, 1, 1], [1, 0, 1, 1], [1, 1, 0, 1], [1, 1, 1, 0]]
num: 4
